#!/usr/bin/env python3
# Wrapper script to find a wpull module.
# Adjust path of Python (3.3, 3.4 etc) as needed.

if __name__ == '__main__':
    # Uncomment below if not installed in Python path.
    # It is recommended that pip install [--user] is used however.
    # import sys
    # sys.path.append('LOCATION_OF_WPULL_PARENT_DIR')
    import faulthandler
    faulthandler.enable()
    import wpull.__main__
    wpull.__main__.main()
