#!/usr/bin/env ruby

require File.expand_path('../lib/archive_bot', __FILE__)

include ArchiveBot::Redis

r = make_redis

all = r.lrange('pending', 0, -1)

r.watch('pending')

res = r.multi do
  all.each { |ident| r.lpush('pending-new', ident) }
  r.del('pending')
  r.rename('pending-new', 'pending')
end

exit res ? 0 : 1
